POST http://localhost:3000/SignUp
content-type: application/json

{
    "username": "Aumaim",
    "password": "311243",
    "email": "",
    "role": "1"
}

###
POST http://localhost:3000/SignIn
content-type: application/json

{
    "username": "punonly",
    "password": "21072643"
}

###
POST  http://localhost:3000/DataCar
content-type: application/json

{
    "type": 2
}


###
POST http://localhost:3000/Addcar
content-type: application/json

{
    "name_car": "รถสองแถว",
    "price_car": "200",
    "capacity": "12"
}
###
POST http://localhost:3000/Editcar
content-type: application/json

{
    "carID": 12,
    "name_car": "taxi",
    "price_car": 500,
    "capacity": 4,
    "TypecarID": 2
}

###const { carID , name_car, price_car, capacity, TypecarID } = req.body;

GET http://localhost:3000/DataHotel
content-type: application/json

###
POST http://localhost:3000/Edithotel
content-type: application/json

{
    "hotelID": 2,
    "name_hotel": "pun",
    "price_per_day": 2000
}

###
GET http://localhost:3000/popularplan
content-type: application/json
